SegundaSecuenciaSemaforos: SegundaSecuenciaSemaforos.c
	gcc SegundaSecuenciaSemaforos.c -o SegundaSecuenciaSemaforos -pthread
	./SegundaSecuenciaSemaforos
	rm SegundaSecuenciaSemaforos

SegundaSecuenciaPipes: SegundaSecuenciaPipes.c
	gcc SegundaSecuenciaPipes.c -o SegundaSecuenciaPipes
	./SegundaSecuenciaPipes
	rm SegundaSecuenciaPipes