ReservaDeAulasHilos: ReservaDeAulasHilos.c
	gcc ReservaDeAulasHilos.c -o ReservaDeAulasHilos -pthread
	./ReservaDeAulasHilos
	rm ReservaDeAulasHilos

ReservaDeAulasProcesos: ReservaDeAulasProcesos.c
	gcc ReservaDeAulasProcesos.c -o ReservaDeAulasProcesos
	./ReservaDeAulasProcesos
	rm ReservaDeAulasProcesos