Minishell: *.c
	gcc cat.c -o cat
	gcc minishell.c -o minishell
	gcc touch.c -o touch
	gcc mkdir.c -o mkdir
	gcc rmdir.c -o rmdir
	gcc chmod.c -o chmod
	gcc ls.c -o ls
	gcc help.c -o help
	./minishell
	rm cat
	rm minishell
	rm touch
	rm mkdir
	rm rmdir
	rm chmod
	rm ls
	rm help

	
	

	
