PrimeraSecuenciaSemaforos: PrimeraSecuenciaSemaforos.c
	gcc PrimeraSecuenciaSemaforos.c -o PrimeraSecuenciaSemaforos -pthread
	./PrimeraSecuenciaSemaforos
	rm PrimeraSecuenciaSemaforos

PrimeraSecuenciaPipes: PrimeraSecuenciaPipes.c
	gcc PrimeraSecuenciaPipes.c -o PrimeraSecuenciaPipes
	./PrimeraSecuenciaPipes
	rm PrimeraSecuenciaPipes